FeedbackBundle_feedback:
        resource: "@FeedbackBundle/Resources/config/routing/feedback.yml"
        prefix:   /feedback
        
FeedbackBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: FeedbackBundle:Default:index }
    
FeedbackBundle_test:
    pattern:   /test
    defaults: { _controller: FeedbackBundle:Default:test }
